# **PYTHON NUMPY**

*   Numpy is an advanced list
* Not just an advanced list, it is faster than the normal list
* Numpy is an array (sequence of number)
*   Numpy is created for computations
* Numpy is a library that has been built in python, and before we can use it, we have to import it
* everything we do like pandas, framework were built under numpy
* Numpy helps to process numbers
* it is a set of function designed to become a package



In [ ]:
## import numpy
#Numpy is a library that has been built in python
# we have to import it

import numpy as np        # as a tradition in python, always import Numpy as np

In [ ]:
## creating a ID NumPy array

array = np.array ([0,1,2,3,4,5,6,7,8,9])       #.array is a method in Numpy that will use to create Numpy kind  of list

#by using .array, it takes it to be a list rather than an array

In [ ]:
type (array)

numpy.ndarray

In [ ]:
# indexing/ slicing

index_array = array[4]
sliced_array = array [2:8]        #it excludes the last number

print (index_array)
print (sliced_array)


4
[2 3 4 5 6 7]


In [ ]:
num =  [5,5,6,8,5,4]
num1 =  [7,8,99,7,86,4]

sum_num = sum (num + num1)
print (sum_num)

244


In [ ]:
from numpy.core.fromnumeric import mean
from numpy.lib.function_base import average

num_avg = average (num)
#num_ mean

print (num_avg)
#print (num_mean)

5.5


# **DIMENSIONAL ARRAYS**

In numpy there is 1D arrays, 2D arrays, 3D arrays

* we use the number of brackets to know the type of dimentional arrays

1D array is just like a normal list because all the items are in one list (no nested list)

In [ ]:
#1D array
# all one dimension arrays are called VECTORS


one_D = np.array ([0,1,2,3,4,5,6,7,8,9,10,11,12])     # all the items are in one list
                                              #it closed with one bracket==iD array

In [ ]:
#2D array

two_D = np.array ([[1,2,3], [4,5,6], [7,8,9,],[5,7,7]])      #it closed with two bracket==2D array

print(two_D)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 7 7]]


In [ ]:
three_D = np.array ([[[1,2,3], [4,5,6], [7,8,9]]])

print(three_D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# indexing in numpy and normal way

#normal way
normal_way = two_D [1,1]

#numpy
np_way = two_D [1,1]

print (normal_way)
print (np_way)

5
5


In [ ]:
#slicing and indexing 2D arrays

print ('item in row1, column2 is: ', two_D [1,2])
print ('first row: ', two_D [0,:])
print ('second column: ', two_D [:,1])
print()
print ('all 2D array: ', two_D [:])

item in row1, column2 is:  6
first row:  [1 2 3]
second column:  [2 5 8 7]

all 2D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 7 7]]


In [ ]:
# to check the shape of the numpy
#shape will tell you the number of rows and column
#while ndim will tell you the dimension

print('shape of the array: ', one_D.shape)
print('shape of the array: ',two_D.shape)
print('shape of the array: ',three_D.shape)

shape of the array:  (10,)
shape of the array:  (3, 3)
shape of the array:  (1, 3, 3)


In [ ]:
# to find the number of dimensions
# we use the '.ndim' attributes

print('Number of dimension (1D): ', one_D.ndim)
print('Number of dimension (2D): ', two_D.ndim)
print('Number of dimension (3D): ', three_D.ndim)


Number of dimension (1D):  1
Number of dimension (2D):  2
Number of dimension (3D):  3


In [ ]:
# data type of the array
#array comes with type and we can find it with the attribute 'dtype'
#dtype is very important in pandas

type1 = one_D.dtype
type2 = two_D.dtype

print(type1)
print(type2)

int64
int64


In [ ]:
#Sum of all element in the array

sum_oneD = one_D.sum()
sum_twoD = two_D.sum()
sum_threeD = three_D.sum()

print ('Sum of all element is', sum_oneD)
print ('Sum of all element is', sum_twoD)
print ('Sum of all element is', sum_threeD)

Sum of all element is 78
Sum of all element is 64
Sum of all element is 45


In [ ]:
#Maximum and minimum item in element

min_oneD = one_D.min()
min_twoD = two_D.min()
min_threeD = three_D.min()

max_oneD = one_D.max()
max_twoD = two_D.max()
max_threeD = three_D.max()

print ('Minimum element is', min_oneD)
print ('Minimum element is', min_twoD)
print ('Minimum element is', min_threeD)
print()
print ('Maximum element is', max_oneD)
print ('Maximum element is', max_twoD)
print ('Maximum element is', max_threeD)


Minimum element is 0
Minimum element is 1
Minimum element is 1

Maximum element is 12
Maximum element is 9
Maximum element is 9


In [ ]:
#mean and standard deviation

mean_oneD = one_D.mean()
mean_twoD = two_D.mean()
mean_threeD = three_D.mean()

std_oneD = one_D.std()
std_twoD = two_D.std()
std_threeD = three_D.std()

Var_oneD = one_D.var()
Var_twoD = two_D.var()
Var_threeD = three_D.var()

print ('mean 1D is:', mean_oneD)
print ('mean 2D is:', mean_twoD)
print ('mean 3D is:', mean_threeD)
print()
print ('Std 1D is:', std_oneD)
print ('Std 1D is:', std_twoD)
print ('Std 1D is:', std_threeD)
print()
print ('Var 1D is:', Var_oneD)
print ('Var 1D is:', Var_twoD)
print ('Var 1D is:', Var_threeD)

mean 1D is: 6.0
mean 2D is: 5.333333333333333
mean 3D is: 5.0

Std 1D is: 3.7416573867739413
Std 1D is: 2.3570226039551585
Std 1D is: 2.581988897471611

Var 1D is: 14.0
Var 1D is: 5.555555555555556
Var 1D is: 6.666666666666667


In [ ]:
#rehsaping an array
#four_D = np.array ([[1,2,3], [4,5,6], [7,8,9]])

#reshaped_twoD = one_D.reshape(2,5)

#print ('mean 1D is:', reshaped_twoD)

# **Testing RANGE WITH numpy and normal list**



In [ ]:
%time list_range = list (range(500))      #list used 23.6 micro second to generate the result

print (list_range)

CPU times: user 17 µs, sys: 2 µs, total: 19 µs
Wall time: 23.6 µs
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208

In [ ]:
%time numpy_range = np.arange(500)       #while numpy used 13 micro second to generate the result
                                              #with the time used, numpy is faster
print (numpy_range)



CPU times: user 53 µs, sys: 4 µs, total: 57 µs
Wall time: 61.8 µs
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 2

# **AXIS**

In [ ]:
## axis
## axis sums each row and also column
## sum by row and create an ID array
## axis 1 sum rows, axis 0 sums colums

print(two_D.sum(axis = 1))			#axis1 is for row #axis 0 is for column (in numpy)
print(three_D.sum(axis = 1))

[ 6 15 24 19]
[[12 15 18]]


In [ ]:
## sum by column and create an ID array

print(two_D.sum(axis = 0)) 			#axis1 is for row #axis 0 is for column (in numpy)
print()
print(three_D.sum(axis = 0))

[17 22 25]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **NUMERIC COMPUTATION**

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,5,5])

print (arr1, arr2)

element addition is [2 7 8]
[1 2 3] [1 5 5]


In [ ]:
## adding 2 list together

result_addition = arr1 + arr2 					## a normal python list cannot do it, it works because is numpy

print ('element addition is', result_addition)

element addition is [2 7 8]


In [ ]:
## dividing 2 list by eachother

result_division = arr1 / arr2 						## a normal python list cannot do it, it works because is numpy
result_division1 = arr2 / arr1          ## there are different

print ('element division is', result_division)
print()
print ('element division is', result_division1)

element division is [1.  0.4 0.6]

element division is [1.         2.5        1.66666667]


In [ ]:
## multipling  an array  by eachother

result_multiplication = arr1 * arr2 						## a normal python list cannot do it, it works because is numpy

print ('element multiplication is', result_multiplication)

element addition is [ 1 10 15]


In [ ]:
## Dot product
## same thing with sumproduct in excel

dot_product = np.dot(arr1, arr2)

print ('element sumproduct is', dot_product)

print()

## OR

dot_product1 = arr1 @ arr2

print ('element sumproduct is', dot_product1)


element sumproduct is 26

element sumproduct is 26


In [ ]:
## combining two arrays together

arr3 = np.array([arr1, arr2])

print (arr3)


[[1 2 3]
 [1 5 5]]


In [ ]:
## Dot product

dot_product4 = np.dot(arr3, arr2)

print ('element sumproduct is', dot_product4)

element sumproduct is [26 51]


# **VECTOR ARRAY**



*  all one dimension arrays are called VECTORS



In [ ]:
arr9 = np.arange(0,20,3)

print (arr9)

[ 0  3  6  9 12 15 18]


In [ ]:
print (arr9 + 2)                # it will add 2 to all the items in the array
                                # it wont affect the former array (arr9)

[ 2  5  8 11 14 17 20]


In [ ]:
arr9                  #it didnt affect it

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
print (arr9 ** 2)

[  0   9  36  81 144 225 324]


# **BOOLEAN ARRAY**

In [ ]:
arr9 > 3

array([False, False,  True,  True,  True,  True,  True])

In [ ]:
arr9 [arr9 > 3]

array([ 6,  9, 12, 15, 18])

In [ ]:
## AND = &
## OR = |
## NOT =  ~

print(arr9 [(arr9 > 3) & (arr9 < 13)])
print(arr9 [(arr9 > 3) & (arr9 > 13)])
print(arr9 [(arr9 > 3) | (arr9 < 13)])
print(arr9 [ (arr9 > 3) & ~ (arr9 < 13)])
print (arr9)

[ 6  9 12]
[15 18]
[ 0  3  6  9 12 15 18]
[15 18]
[ 0  3  6  9 12 15 18]


In [ ]:
# to get even numbers

arr9 [arr9 % 2 == 0]

array([ 0,  6, 12, 18])

In [ ]:
# to get odd numbers

arr9 [ ~ arr9 % 2 == 0]

array([ 3,  9, 15])

In [ ]:
# generate random numbers

RandNum = np.arange (10,100,10)       # it will generate a range that will start from 10 and also inmultiples of 10

print (RandNum)


RandNum1 = np.random.randint (100,size=10)         #return random numbers of any form
#not sorted, not in multiples of anything

print (RandNum1)

[10 20 30 40 50 60 70 80 90]
[22 47 72 36 92 60 66 69 22 15]


In [ ]:
# using for loop to generate a random that will print each number one after the other like raffle draw

for number in range (len (RandNum1) + 1):
  print (np.random.choice (RandNum1))

22
92
60
15
47
22
66
36
66
22
92
